### PR TITLE
Use sphinx-nefertiti theme

### PR DESCRIPTION
**Pull request by danirus**
Hello there, I have developed a Sphinx theme called Nefertiti for Sphinx, that I think it is slightly better than the sphinx_rtd_theme. I have updated your `docs/conf.py` to give it a try with your project. I would very much like if you would decide to use it. I will attach a screenshot of how chatnoir-resiliparse's docs look with it.
Screenshot 2024-11-29 at 23 00 11

I hope you like it.
I have done a bit of customization to add the logo. Also, the `:no-index:` I add to the `docs/api/parse/html.rst`is to avoid one of the warnings when build the docs.
Thanks :-)

### CODE REVIEW

**Comment by danirus** [comment]
I pushed a change to `style.css` that changes the `background-color` when the user prefers the 'light` color-scheme. It overwrites the background color to white. Having the background as white makes a bit more difficult to distinguish the background of code blocks. Maybe it can be overwritten with pygments. I will check.

**Comment by danirus** [comment]
I have tried a few different values for `pygments_light_style`, in the setting `html_theme_options`, in `conf.py`. Some of them give a bit more contrast between the white background and the color of code blocks. But it is a matter of personal choice. I could suggest you any of `gruvbox-light`, `paraiso-light`, `solarized-light`, or `tango`. A list of available pygments are [here](https://sphinx-nefertiti.readthedocs.io/latest/users-guide/customization/pygments.html#available-styles). I haven't tested all of them.

**Comment by phoerious** [comment]
It's certainly more than just personal preference.
image

The red does pass the AAA requirements, but due to the colour combination, it actually looks worse than the grey text.

**Comment by danirus** [comment]
Thanks for considering it anyway.
All the best to you 🙂

**Pull request closed without merging**
